CREATE DATABASE IF NOT EXISTS pai_prompt_agents;

CREATE USER IF NOT EXISTS 'pai_app'@'localhost' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON pai_prompt_agents.* TO 'pai_app'@'localhost';
FLUSH PRIVILEGES;

USE pai_prompt_agents;

CREATE TABLE IF NOT EXISTS PromptHistory (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  SystemPrompt TEXT,
  UserPrompt TEXT NOT NULL,
  ModelReply MEDIUMTEXT,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(50) NOT NULL UNIQUE,
  Email VARCHAR(120) NOT NULL UNIQUE,
  PasswordEncoded VARCHAR(255) NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
